# Use the official Nginx image as the base image
FROM nginx:alpine

# Copy static website files to the Nginx default content directory
COPY . /usr/share/nginx/html

# Expose port 80 for the web server
EXPOSE 80

