
---

### **Markdown File 2: YAML Assignment Questions**

``` 
# YAML Assignment Questions

## Question 1: Kubernetes Deployment
Write a YAML configuration for a Kubernetes Deployment with:
- 3 replicas.
- An Nginx container with the `latest` tag.
- Port 80 exposed.

---

## Question 2: Ansible Playbook
Create an Ansible playbook to:
- Install Apache.
- Start and enable the Apache service.

---

## Question 3: GitHub Actions Workflow
Design a GitHub Actions workflow to:
- Run on `push` events.
- Use Node.js 16.
- Install dependencies and run tests.
```



# Solutions to the above assignments

# Solution 1: Kubernetes Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

# Solution 2: Ansible Playbook
- name: Manage Apache
  hosts: all
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: true

# Solution 3: GitHub Actions Workflow
name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

