name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Build CICD Pipeline Framework Image
    - name: Build CICD Pipeline Framework
      working-directory: Project_Implementation/cicd-pipeline-framework
      run: docker build . --file Dockerfile --tag cicd-pipeline:$(date +%s)
      
    # You can add more builds for other projects
    # - name: Build Microservices Platform
    #   working-directory: Project_Implementation/Microservices_platform
    #   run: docker build . --file Dockerfile --tag microservices:$(date +%s)
